using System;

namespace Lski.Toolbox.Txt {

	/// <summary>
	/// States the types of characters that will be included in the Random String generated by RandomString
	/// </summary>
	[Flags]
	public enum CharacterListOptions : byte {

		/// <summary>
		/// Include uppercase letters
		/// </summary>
		/// <remarks></remarks>
		UppercaseLetters = 1,

		/// <summary>
		/// Include lowercase letters
		/// </summary>
		/// <remarks></remarks>
		LowercaseLetters = 2,

		/// <summary>
		/// Include numbers 0-9
		/// </summary>
		/// <remarks></remarks>
		Numbers = 4,

		/// <summary>
		/// Include underscores (best used in combination with other options)
		/// </summary>
		/// <remarks></remarks>
		Underscores = 8,

		/// <summary>
		/// Include hyphens (best used in combination with other options)
		/// </summary>
		/// <remarks></remarks>
		Hyphens = 16,

		/// <summary>
		/// Other punctuation not typically included in a random string
		/// </summary>
		OtherPunctuation = 32,

		/// <summary>
		/// Include both lower and upper case letters
		/// </summary>
		/// <remarks></remarks>
		Letters = (UppercaseLetters | LowercaseLetters),

		/// <summary>
		/// Include all upper and lower case letters and numbers
		/// </summary>
		/// <remarks></remarks>
		AlphaNumerics = (Letters | Numbers),

		/// <summary>
		/// Include all options
		/// </summary>
		/// <remarks></remarks>
		All = (AlphaNumerics | Underscores | Hyphens | OtherPunctuation)
	}
}